name: Appium tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tests repo
        uses: actions/checkout@v4

      - name: Checkout BudgetPilot
        uses: actions/checkout@v4
        with:
          repository: petryniy1/BudgetPilot
          path: BudgetPilot

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run tests on Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          script: |
            cd BudgetPilot
            chmod +x gradlew
            ./gradlew assembleDebug
            adb install -r app/build/outputs/apk/debug/app-debug.apk